MovieDreamers/movies/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'movies'
urlpatterns = [
path('',views.home, name='home'),
    path('list', views.index, name='index'),   #/movies
    path('<int:movie_id>/', views.detail, name='detail'),   #/movies/1/
    path('<int:movie_id>/leave_comment/', views.leave_comment, name='leave_comment'),

    path('search/', views.search, name='search'),
path('signup/' , views.signup , name = 'signup'), #/register
path('final_buy/', views.final_buy , name = 'final_buy'),

path('buy/<int:session_id>/', views.buy_ticket , name = 'buy_ticket'),
path('profile/' , views.profile , name = 'profile'),
path('logout/' , views.my_logout , name = 'my_logout'),
url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),


    
]

MovieDreamers/untitled/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth.views import auth_login
from movies import views as movies_views
from django.urls import path, include
urlpatterns = [

    path('movies/', include('movies.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('signup/' , movies_views.signup , name = 'signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', movies_views.home , name = 'home')
]

MovieDreamers/movies/models.py
# that thing where we say what will be in our database (like movie title , primere date and etc.)
import datetime
from django.db import models

from django.utils import timezone


class Movie(models.Model):
    film_id = models.IntegerField('film_id')

    movie_title = models.CharField('Movie title', max_length=200)

    movie_imdb = models.FloatField('IMDB score')

    movie_description = models.TextField('Movie Description')

    movie_published_date = models.DateTimeField('published date')

    movie_genre = models.CharField('Movie genres', max_length=200)

    def __str__(self):
        return self.movie_title

    def was_published_resently(self):
        return self.movie_published_date >= (timezone.now() - datetime.timedelta(days=7))


class Cities(models.Model):
    name = models.CharField('City', max_length=25)
    tag = models.CharField('tag', max_length=25)


class Cinema(models.Model):
    theatre_id = models.IntegerField('theatres_id')
    cinema_id = models.IntegerField('cinema_id')
    city_id = models.IntegerField('city_id')
    cinema_name = models.CharField('City', max_length=40)
    cinema_adress = models.CharField('City', max_length=200)


class Ticket(models.Model):
    ticket_name = models.CharField('Ticket name', max_length=20)
    ticket_sum = models.IntegerField('Ticket price')


class Sessions(models.Model):
    film_id = models.IntegerField("film_id_for_session")
    cinema_id = models.IntegerField("cinema_id_for_session")
    ts = models.IntegerField("ts")
    session_id = models.IntegerField("session_id")

    session_date = models.CharField('Session_date', max_length=30)
    session_time = models.CharField('Session_time', max_length=30)
    session_hall = models.CharField('Session hall', max_length=30)


class Comment(models.Model):
    movie = models.ForeignKey(Movie,
                              on_delete=models.CASCADE)  # CASECADE delete all comments when movie will be deleted
    author_name = models.CharField('Author of comment', max_length=50)
    comment_text = models.CharField('Comment', max_length=200)

    def __str__(self):
        return self.author_name

MovieDreamers/movies/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
  email = forms.EmailField(max_length=254, help_text='Это поле обязательно')

  class Meta:
    model = User
    fields = ('username', 'email')

MovieDreamers/movies/views.py
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Movie, Comment, Cities, Cinema, Ticket, Sessions
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import SignUpForm
from django.contrib.auth import authenticate, login
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignUpForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
import smtplib


def home(request):

    needed_cinemas = None
    needed_movies = []
    movies_list = Movie.objects.order_by("movie_published_date")[:6]

    cities_list = Cities.objects.all()
    cinemas = Cinema.objects.all()
    if request.method == "POST":
        cities_list = Cities.objects.all()
        cinemas = Cinema.objects.all()
        city = request.POST.get('city')
        print(city)
        # city = "Алматы"
        needed_city = Cities.objects.filter(name=city)
        print(needed_city)
        city_id = needed_city[0].id
        print(city_id)
        if needed_city is not None:
            print("found needed city")

            needed_cinemas = Cinema.objects.filter(city_id=city_id)
            for i in range(len(needed_cinemas)):
                print(needed_cinemas[i].cinema_name)

            cinema = request.POST.get('cinema')
            chosen_cinema = Cinema.objects.filter(cinema_name=cinema)
            chosen_cinema_id = chosen_cinema[0].theatre_id
            print(chosen_cinema_id)
            needed_sessions = Sessions.objects.filter(cinema_id=chosen_cinema_id)

            print(needed_sessions)
            for i in range(len(needed_sessions)):
                needed_movies += Movie.objects.filter(film_id=needed_sessions[i].film_id)

            print(needed_movies)

            return render(request, 'home.html',
                              {'cinemas': needed_cinemas, 'cities': cities_list, 'sessions': needed_sessions,
                               'movies': needed_movies})

    return render(request, 'home.html', {'cities': cities_list, 'cinemas': cinemas, 'movies_list': movies_list})



def index(request):
    latest_movies_list = Movie.objects.order_by('movie_published_date')[:12]
    cities_list = Cities.objects.all()
    print(latest_movies_list[0].movie_title)
    return render(request, 'movies/list.html', {'latest_movies_list': latest_movies_list, 'cities_list': cities_list})


def detail(request, movie_id):
    try:
        global seen_movies


        m = Movie.objects.get(id=movie_id)
        


    except:
        raise Http404("No such movie")
    cities = []
    cinemas = []
    needed_sessions= []
    needed_cities=[]
    sessions_list= Sessions.objects.filter(film_id=m.film_id)
    for session in sessions_list:



        cinema = Cinema.objects.filter(theatre_id= session.cinema_id)

        if cinema is not None:

            needed_sessions.append(session)
            for cinema1 in cinema:
                cinemas.append(cinema1)

  

    need_cinema =[]


    print(len(need_cinema))
    print(need_cinema)
    print(cinemas)
    print("----------------------------------------------------")
    print(needed_sessions)
    print("------------------------------------------------------")
    
    latest_comment_list = m.comment_set.order_by('-id')[:10]

    return render(request, 'movies/detail.html', {'movie': m, 'latest_comment_list': latest_comment_list , 'sessions' :needed_sessions,'cinemas':cinemas } )


def leave_comment(request, movie_id):
    try:
        user = request.user
        m = Movie.objects.get(id=movie_id)
    except:
        raise Http404("No such movie")

    m.comment_set.create(author_name=user.username, comment_text=request.POST.get('text'))

    return HttpResponseRedirect(reverse('movies:detail', args=(m.id,)))


def search(request):
    search_res = []
    if request.method == "POST":
        print("Post worked ")
        movie_description = request.POST.get('input')
        print(movie_description)
        if len(movie_description) > 0:
            search_res = Movie.objects.filter(movie_title__contains=movie_description)
        return render(request, "movies/search.html",
                      {"search_res": search_res, "empty_res": "There is no such movie1"})


# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             form.save()
#         username = form.cleaned_data.get('username')
#         my_password = form.cleaned_data.get('password1')
#         user = authenticate(username=username, password=my_password)
#         login(request, user)
#         return render(request, 'home.html', {'user': user})
#     else:
#
#         return auth_views.signin(request)


def profile(request):
    return render(request, "registration/profile.html")


def my_logout(request):
    redirect('home.html')
    return auth_views.logout(request)


# def cities_list(request):
#     cities_list = Cities.objects.all()
#     return render(request,'home.html', {'cities_list' : cities_list})

def email_sender(input_message, email_to, client):
    ''' function to send email '''
    to = email_to
    gmail_user = 'ayannaimankhan@gmail.com'  ## email of sender account
    gmail_pwd = 'Superpassword'  ## password of sender account
    smtpserver = smtplib.SMTP("smtp.gmail.com", 587)
    smtpserver.ehlo()
    smtpserver.starttls()
    smtpserver.ehlo()
    smtpserver.login(gmail_user, gmail_pwd)
    header = 'To:' + to + '\n' + 'From: ' + gmail_user + '\n' + 'Subject:Authenticate your account For MovieDreamers.com! \n'
    input_message = input_message + client
    msg = header + input_message
    smtpserver.sendmail(gmail_user, to, msg)
    smtpserver.close()
    print("EMAIL SENT")


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('registration/acc_active_html.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email_sender(message, to_email, user.username)
            email.send()
            print("email sent to" + user.email)
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return render(request, "home.html")
    else:
        return ('Activation link is invalid!')




def final_buy(request):
    if request.method == "POST":
        user = request.user
        time = request.POST.get('time')
        seats = request.POST.get('seats')
        price =request.POST.get('price')
        msg = "YOU have just bought a ticket ! My congratulations comrade! That you eveded all bugs of this  site and could buy a ticket! "
        email_sender(msg, user.email, user.username)
        return HttpResponse("Successfully bought ! Check up your gmail))")

    return render(request, "movies/place.html")


def buy_ticket(request, session_id):
    if request.method == "POST":

        need_sessions = Sessions.objects.filter(id=session_id)
        date = need_sessions[0].session_date
        time = need_sessions[0].session_time
        needed_films = Movie.objects.filter(film_id=need_sessions[0].film_id)
        needed_film_title = str(needed_films[0].movie_title)

        return render(request, "movies/place.html" , {'date' : date , 'time': time , 'film': needed_film_title})
    return HttpResponse("Bought failed")

MovieDreamers/templates/movies/detail.html
{% block title %}{{movie.movie_title}}{% endblock %}
<head>
{% load staticfiles %}
     <link rel="stylesheet" href="{%static 'css/Featured-Movies-1.css'%}?20191212">
      <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
</head>
{% block content %}

    <img src='{{ movie.movie_picture_url }}'>

   <h2>{{movie.movie_title}}</h2>

    <p>{{ movie.movie_description | safe }}</p>


   <p>{{ movie.get_rating_display}}</p>


    <em>{{ movie.movie_published_date}}</em>
    <hr>
{% if latest_comment_list %}
    {% for a in latest_comment_list %}
        <p>
        <strong>{{ a.author_name }}</strong>
        <p>{{a.comment_text}}</p>
        </p>
{% endfor %}
    {% else %}
    Comments didn't find ! Be the first!)

    {% endif %}
    <hr>
{% if user.is_authenticated %}
    <form action="{% url 'movies:leave_comment' movie.id %}" method="POST">

    {% csrf_token %}



    <textarea name="text" required = "" placeholder="Your text" cols = "30" rows = "10"></textarea><br>

    <button type ="submit"> Leave comment </button>
    </form>
{%else%}
To leave comment please sign up first!

{%endif%}
<p >Session with this movie</p>
<div class = "container-name">
    <form class="row" >

<div class="element1 col-md-5">

         {%for cinema in cinemas %}
         <ol>
             <li value = "{{forloop.counter}}">
                 {{cinema.cinema_name}}
                 {{cinema.cinema_adress}}
             </li>
         </ol>

         {%endfor%}

     </div>

         <div class="element2 col-md-7">
         {%for session in sessions%}

         <ol>

             Дата:{{session.session_date}}
            Время:{{session.session_time}}
            Зал:{{session.session_hall}}

             <form action="{%url 'movies:buy_ticket' session.id%}" method="post">
             {% csrf_token %}
<button method = 'POST' type="submit">Buy ticket</button>
             </form>

         </ol>


         {%endfor%}
             </div>
</form>
</div>

{% endblock %}

MovieDreamers/templates/movies/place.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	{% load staticfiles %}
<title>Movie Ticket Booking Widget Flat Responsive Widget Template :: w3layouts</title>
<!-- for-mobile-apps -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<meta name="keywords" content="Movie Ticket Booking Widget Responsive, Login form web template, Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<!-- //for-mobile-apps -->
<link href='//fonts.googleapis.com/css?family=Kotta+One' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<link href="{%static 'css/place.css'%}" rel="stylesheet" type="text/css" media="all" />
<script src="{%static 'js/jquery-1.11.0.min.js'%}"></script>
<script src="{%static 'js/jquery.seat-charts.js'%}"></script>
</head>
<body>
<div class="content">
	<h1>Movie Ticket Booking Widget</h1>
	<div class="main">
		<h2>Multiplex Theatre Showing Screen 1</h2>
		<form action="{%url 'movies:final_buy'%}" method="post">
			{% csrf_token %}
		<div class="demo">
			<div id="seat-map">

				<div class="front">SCREEN</div>					
			</div>

			<div class="booking-details">
				<ul class="book-left">
					<li><p>Movie</p> </li>
					<li >Time </li>
					<li>Tickets</li>
					<li>Total</li>
					<li>Seats :</li>
				</ul>
				<ul class="book-right">
					<li name = "film" method = 'POST'>: {{film}}<input type="hidden" name="film" value="{{film}}"></li>
					<li name = "time" method = 'POST'>: {{date}}, {{time}}<input type="hidden" name="time" value="{{date}}, {{time}}"></li>
					<li name = "num" method = 'POST'>: <span id="counter">0</span><input type="hidden" name="seats" value="0"></li>
					<li name = "price" method = 'POST'>: <b><i>$</i><span id="total">0</span></b><input type="hidden" name="price" ></li>
				</ul>
				<div class="clear"></div>
				<ul id="selected-seats" class="scrollbar scrollbar1" name = "seats" method = 'POST' ><input type="hidden" name="price" ></ul>
			

				<button class="checkout-button" method = 'POST' type="submit">Book Now</button>

				<div id="legend"></div>



			</div>

			<div style="clear:both"></div>
	    </div>
		</form>
			<script type="text/javascript">
				var price = 10; //price
				$(document).ready(function() {
					var $cart = $('#selected-seats'), //Sitting Area
					$counter = $('#counter'), //Votes
					$total = $('#total'); //Total money
					
					var sc = $('#seat-map').seatCharts({
						map: [  //Seating chart
							'aaaaaaaaaa',
							'aaaaaaaaaa',
							'__________',
							'aaaaaaaa__',
							'aaaaaaaaaa',
							'aaaaaaaaaa',
							'aaaaaaaaaa',
							'aaaaaaaaaa',
							'aaaaaaaaaa',
							'__aaaaaa__'
						],
						naming : {
							top : false,
							getLabel : function (character, row, column) {
								return column;
							}
						},
						legend : { //Definition legend
							node : $('#legend'),
							items : [
								[ 'a', 'available',   'Available' ],
								[ 'a', 'unavailable', 'Sold'],
								[ 'a', 'selected', 'Selected']
							]					
						},
						click: function () { //Click event
							if (this.status() == 'available') { //optional seat
								$('<li>Row'+(this.settings.row+1)+' Seat'+this.settings.label+'</li>')
									.attr('id', 'cart-item-'+this.settings.id)
									.data('seatId', this.settings.id)
									.appendTo($cart);

								$counter.text(sc.find('selected').length+1);
								$total.text(recalculateTotal(sc)+price);
											
								return 'selected';
							} else if (this.status() == 'selected') { //Checked
									//Update Number
									$counter.text(sc.find('selected').length-1);
									//update totalnum
									$total.text(recalculateTotal(sc)-price);
										
									//Delete reservation
									$('#cart-item-'+this.settings.id).remove();
									//optional
									return 'available';
							} else if (this.status() == 'unavailable') { //sold
								return 'unavailable';
							} else {
								return this.style();
							}
						}
					});
					//sold seat
					sc.get(['1_2', '4_4','4_5','6_6','6_7','8_5','8_6','8_7','8_8', '10_1', '10_2']).status('unavailable');
						
				});
				//sum total money
				function recalculateTotal(sc) {
					var total = 0;
					sc.find('selected').each(function () {
						total += price;
					});
							
					return total;
				}
			</script>
	</div>
	<p class="copy_rights">&copy; 2019 Movie Ticket Booking Widget. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank"> MovieDreamers</a></p>
</div>
<script src="js/jquery.nicescroll.js"></script>
<script src="js/scripts.js"></script>
</body>
</html>