MovieDreamers/movies/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'movies'
urlpatterns = [
path('',views.home, name='home'),
    path('list', views.index, name='index'),   #/movies
    path('<int:movie_id>/', views.detail, name='detail'),   #/movies/1/
    path('<int:movie_id>/leave_comment/', views.leave_comment, name='leave_comment'),

    path('search/', views.search, name='search'),
path('signup/' , views.signup , name = 'signup'), #/register
path('final_buy/', views.final_buy , name = 'final_buy'),

path('buy/<int:session_id>/', views.buy_ticket , name = 'buy_ticket'),
path('profile/' , views.profile , name = 'profile'),
path('logout/' , views.my_logout , name = 'my_logout'),
url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),


    
]

MovieDreamers/untitled/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth.views import auth_login
from movies import views as movies_views
from django.urls import path, include
urlpatterns = [

    path('movies/', include('movies.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('signup/' , movies_views.signup , name = 'signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', movies_views.home , name = 'home')
]

MovieDreamers/templates/index.html
<html>

<head>

    {% load static %}
    <meta charset="UTF-8">
    <title>MovieDreamers</title>

    <link href="{% static 'css/style.css'%}?20191205" rel="stylesheet" type="text/css">



</head>
<body>
{% csrf_token %}
<header id="head">
    <h1>MovieDreamers</h1>
    <a class="h_icon" href="#" id="film"><img alt="film_icon" src="{% static 'img/film.png' %}">
        <div class="hiden"></div>
    </a>
    <a class="h_icon" href="#" id="child"><img alt="child_icon" src="{% static 'img/child.png' %}">
        <div class="hiden"></div>
    </a>
    <a class="h_icon" href="#" id="calendar"><img alt="calendar_icon" src="{% static 'img/calendar.png' %}">
        <div class="hiden"></div>
    </a>
    <a class="h_icon" href="#" id="list"><img alt="list_icon" src="{% static 'img/list.png' %}">
        <div class="hiden"></div>
    </a>
    <form>
        <select>

        </select>
    </form>
        {% block login %}


    <a href="{%url 'movies:profile'%}">
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}
</a>

  <form id="content" action="{%url 'movies:search'%}"  method="post">
        {% csrf_token %}
        <input class="input" id="search-input" name="input" type="text" method = 'POST' placeholder="LOOKING FOR MOVIES?">
        <button class="search" id="search-btn" type="submit" value="Search" name = "Search"></button>
    </form>

    </a>
</header>
<div id="wwy">
    <div id="ImgBot">
    </div>
    {%block content%}
    {% if cities_list %}
            hi
        {%for city in cities_list%}
            {{city.name}}
        {%endfor%}
    {%else%}
    no
    {%endif%}
    {%endblock%}
</div>

</body>
<script src="{% static 'js/script.js' %}"></script>
<footer>

  </footer>
</html>